import React from 'react';
import Layout from '@/components/Layout';

const features = [
  {
    icon: '🔍',
    title: 'AI Content Detection',
    description:
      'Analyzes text patterns, writing signatures, and linguistic markers to identify content likely generated by AI models.',
  },
  {
    icon: '🖼️',
    title: 'Screenshot & Image Analysis',
    description:
      'Scans uploaded images and screenshots for manipulation artifacts, metadata inconsistencies, and AI generation fingerprints.',
  },
  {
    icon: '📡',
    title: 'Credibility & Risk Signals',
    description:
      'Surfaces contextual trust signals — source reliability, propagation patterns, and risk indicators — in seconds.',
  },
  {
    icon: '🎯',
    title: 'Radar-Style Confidence Results',
    description:
      'Results displayed as an intuitive confidence score on a radar dial — clear, visual, and immediately actionable.',
  },
  {
    icon: '⚡',
    title: 'Fast & Simple Experience',
    description:
      'Paste, upload, or link — get your trust assessment in under 10 seconds. No account required to try it.',
  },
];

const notYet = [
  'Browser extensions',
  'Enterprise tooling & APIs',
  'Full social media monitoring',
  'Advanced deepfake detection systems',
  'Mobile applications',
  'Payment & subscription systems',
  'Complex analytics dashboards',
];

const RadarVisual = () => (
  <div className="relative mx-auto mb-12 float-up" style={{ width: 200, height: 200 }}>
    {/* Scan ring ping */}
    <div
      className="scan-ring absolute rounded-full border border-cyan-400/40"
      style={{ width: 160, height: 160, top: '50%', left: '50%' }}
    />
    {/* Concentric rings */}
    {[56, 96, 136, 176].map((size, i) => (
      <div
        key={i}
        className="absolute rounded-full border border-cyan-500/20"
        style={{
          width: size,
          height: size,
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%)',
        }}
      />
    ))}
    {/* Crosshairs */}
    <div className="absolute top-1/2 left-0 right-0 h-px bg-cyan-500/15" />
    <div className="absolute left-1/2 top-0 bottom-0 w-px bg-cyan-500/15" />
    {/* Rotating sweep */}
    <div
      className="absolute inset-0 rounded-full radar-sweep"
      style={{
        background:
          'conic-gradient(from 0deg, transparent 280deg, rgba(34,211,238,0.12) 330deg, rgba(34,211,238,0.5) 360deg)',
      }}
    />
    {/* Center dot */}
    <div
      className="absolute glow-pulse rounded-full bg-cyan-400"
      style={{
        width: 10,
        height: 10,
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
      }}
    />
    {/* Blips */}
    <div
      className="absolute rounded-full bg-cyan-400 glow-pulse"
      style={{ width: 7, height: 7, top: '28%', left: '66%' }}
    />
    <div
      className="absolute rounded-full bg-blue-400"
      style={{ width: 5, height: 5, top: '63%', left: '32%', opacity: 0.8 }}
    />
    <div
      className="absolute rounded-full bg-cyan-300"
      style={{ width: 4, height: 4, top: '45%', left: '72%', opacity: 0.6 }}
    />
  </div>
);

export default function AiRadar() {
  return (
    <Layout>
      <div
        style={{
          background: 'linear-gradient(160deg, #060d1a 0%, #0a1628 45%, #05111f 100%)',
          minHeight: '100vh',
        }}
      >
        {/* ── Hero ───────────────────────────────────────────── */}
        <section className="relative overflow-hidden pt-16 pb-20 px-6 flex flex-col items-center text-center">
          {/* Background grid */}
          <div
            className="absolute inset-0 pointer-events-none"
            style={{
              backgroundImage:
                'linear-gradient(rgba(34,211,238,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(34,211,238,0.04) 1px, transparent 1px)',
              backgroundSize: '60px 60px',
            }}
          />

          <RadarVisual />

          <div
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border text-xs font-semibold tracking-widest uppercase mb-5"
            style={{
              borderColor: 'rgba(34,211,238,0.3)',
              background: 'rgba(34,211,238,0.06)',
              color: '#67e8f9',
            }}
          >
            <span
              className="w-1.5 h-1.5 rounded-full bg-cyan-400 glow-pulse"
              style={{ display: 'inline-block' }}
            />
            Powered by IntelliXar
          </div>

          <h1
            className="text-6xl md:text-8xl font-black text-white tracking-tight mb-3 leading-none"
          >
            AI{' '}
            <span
              style={{
                color: '#22d3ee',
                textShadow: '0 0 60px rgba(34,211,238,0.6), 0 0 120px rgba(34,211,238,0.2)',
              }}
            >
              Radar
            </span>
          </h1>

          <p
            className="text-2xl md:text-3xl font-light mb-6 tracking-wider"
            style={{ color: '#a5f3fc' }}
          >
            Know What&apos;s Real.
          </p>

          <p className="text-gray-300 text-lg max-w-lg leading-relaxed mb-10">
            AI Radar is a digital trust tool that helps users detect AI-generated and
            manipulated content using intelligent analysis and credibility signals.
          </p>

          <div className="flex gap-4 flex-wrap justify-center">
            <button
              className="px-8 py-3 rounded-full font-bold text-black text-base transition-all duration-200 hover:scale-105"
              style={{
                background: '#22d3ee',
                boxShadow: '0 0 28px rgba(34,211,238,0.45)',
              }}
            >
              Join Waitlist
            </button>
            <button
              className="px-8 py-3 rounded-full font-semibold text-base transition-all duration-200 hover:bg-cyan-500/10"
              style={{
                color: '#22d3ee',
                border: '1px solid rgba(34,211,238,0.4)',
              }}
            >
              Learn More
            </button>
          </div>
        </section>

        {/* ── Mission ────────────────────────────────────────── */}
        <section className="px-6 py-14 flex justify-center">
          <div
            className="max-w-3xl w-full rounded-2xl p-px"
            style={{
              background:
                'linear-gradient(135deg, rgba(34,211,238,0.35) 0%, rgba(59,130,246,0.15) 100%)',
            }}
          >
            <div
              className="rounded-2xl px-8 md:px-14 py-12 text-center"
              style={{
                background: 'rgba(6,13,26,0.96)',
                backdropFilter: 'blur(20px)',
              }}
            >
              <p
                className="text-xs font-bold tracking-widest uppercase mb-5"
                style={{ color: '#67e8f9' }}
              >
                Our Mission
              </p>
              <p className="text-white text-xl md:text-2xl font-medium leading-relaxed">
                &ldquo;AI Radar helps people quickly identify, analyze, and verify
                AI-generated or manipulated content so they can make{' '}
                <span style={{ color: '#22d3ee' }}>more informed decisions online.</span>
                &rdquo;
              </p>
            </div>
          </div>
        </section>

        {/* ── Features ───────────────────────────────────────── */}
        <section className="px-6 py-16 max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <p
              className="text-xs font-bold tracking-widest uppercase mb-3"
              style={{ color: '#67e8f9' }}
            >
              Capabilities
            </p>
            <h2 className="text-3xl md:text-4xl font-bold text-white">
              What AI Radar Does
            </h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {features.map((f, i) => (
              <div
                key={i}
                className="rounded-xl p-6 group cursor-default transition-all duration-300 hover:scale-[1.02]"
                style={{
                  background: 'rgba(255,255,255,0.03)',
                  border: '1px solid rgba(255,255,255,0.06)',
                  backdropFilter: 'blur(12px)',
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.borderColor = 'rgba(34,211,238,0.3)';
                  e.currentTarget.style.boxShadow = '0 0 24px rgba(34,211,238,0.08)';
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.borderColor = 'rgba(255,255,255,0.06)';
                  e.currentTarget.style.boxShadow = 'none';
                }}
              >
                <div className="text-3xl mb-4">{f.icon}</div>
                <h3 className="text-white font-semibold text-lg mb-2">{f.title}</h3>
                <p className="text-gray-400 text-sm leading-relaxed">{f.description}</p>
              </div>
            ))}

            {/* Spacer card — decorative */}
            <div
              className="rounded-xl p-6 flex flex-col items-center justify-center text-center sm:col-span-2 lg:col-span-1"
              style={{
                background:
                  'linear-gradient(135deg, rgba(34,211,238,0.06) 0%, rgba(59,130,246,0.06) 100%)',
                border: '1px dashed rgba(34,211,238,0.2)',
              }}
            >
              <div
                className="text-4xl mb-3 glow-pulse"
                style={{ color: '#22d3ee', display: 'inline-block' }}
              >
                📡
              </div>
              <p className="text-cyan-300 text-sm font-medium">More capabilities incoming</p>
              <p className="text-gray-500 text-xs mt-1">Built with focus. Shipped with speed.</p>
            </div>
          </div>
        </section>

        {/* ── Not Yet ────────────────────────────────────────── */}
        <section className="px-6 py-16 max-w-4xl mx-auto">
          <div
            className="rounded-2xl p-8 md:p-12"
            style={{
              background: 'rgba(255,255,255,0.02)',
              border: '1px solid rgba(255,255,255,0.05)',
              backdropFilter: 'blur(10px)',
            }}
          >
            <div className="text-center mb-10">
              <p
                className="text-xs font-bold tracking-widest uppercase mb-3"
                style={{ color: '#93c5fd' }}
              >
                Roadmap Clarity
              </p>
              <h2 className="text-2xl md:text-3xl font-bold text-white mb-3">
                What AI Radar Doesn&apos;t Do Yet
              </h2>
              <p className="text-gray-500 text-sm max-w-md mx-auto">
                We&apos;re building with focus, not fear. The MVP is deliberately scoped to
                do one thing exceptionally well — then grow from there.
              </p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {notYet.map((item, i) => (
                <div key={i} className="flex items-center gap-3">
                  <div
                    className="w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0"
                    style={{ border: '1px solid rgba(255,255,255,0.12)' }}
                  >
                    <div
                      className="w-1.5 h-1.5 rounded-full"
                      style={{ background: 'rgba(255,255,255,0.2)' }}
                    />
                  </div>
                  <span className="text-gray-400 text-sm">{item}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── CTA ────────────────────────────────────────────── */}
        <section className="px-6 py-24 text-center relative overflow-hidden">
          {/* Glow backdrop */}
          <div
            className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full pointer-events-none"
            style={{
              width: 500,
              height: 500,
              background:
                'radial-gradient(circle, rgba(34,211,238,0.07) 0%, transparent 70%)',
            }}
          />

          <div className="relative max-w-2xl mx-auto">
            <p
              className="text-xs font-bold tracking-widest uppercase mb-5"
              style={{ color: '#67e8f9' }}
            >
              Early Access
            </p>
            <h2 className="text-4xl md:text-6xl font-black text-white mb-5 leading-tight">
              Be Early to{' '}
              <span
                style={{
                  color: '#22d3ee',
                  textShadow:
                    '0 0 40px rgba(34,211,238,0.5), 0 0 80px rgba(34,211,238,0.2)',
                }}
              >
                Digital Trust.
              </span>
            </h2>
            <p className="text-gray-400 text-lg mb-10 max-w-md mx-auto leading-relaxed">
              AI Radar is launching soon. Get early access and help shape the future of
              content verification.
            </p>
            <div className="flex gap-4 justify-center flex-wrap">
              <button
                className="px-10 py-4 rounded-full font-bold text-black text-lg transition-all duration-200 hover:scale-105"
                style={{
                  background: '#22d3ee',
                  boxShadow: '0 0 36px rgba(34,211,238,0.45)',
                }}
              >
                Join Waitlist
              </button>
              <button
                className="px-10 py-4 rounded-full font-bold text-lg transition-all duration-200 hover:bg-cyan-500/10"
                style={{
                  color: '#22d3ee',
                  border: '1px solid rgba(34,211,238,0.4)',
                }}
              >
                Learn More
              </button>
            </div>
          </div>
        </section>
      </div>
    </Layout>
  );
}
